/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu.dash;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;

import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
//import javax.print.DocFlavor;

/**
 *
 * @author Mon PC
 */
public class AFFECTER extends javax.swing.JFrame {
    connexion conn= new connexion();
    Statement stm;
    ResultSet resultat;
    DefaultTableModel model= new DefaultTableModel();

    /**
     * Creates new form AFFECTER
     */
    @SuppressWarnings("empty-statement")
    public AFFECTER() {
        initComponents();
         model.addColumn("N°AFFECT");
        model.addColumn("N°EMPLOYEE");
        model.addColumn("ANCIEN LIEU");
        model.addColumn("NOUVEAU LIEU");
       model.addColumn("DATE AFFECT");
        model.addColumn("DATE PRISE SERVICE");
        
          try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
  ResultSet resultat = stm.executeQuery("Select *  from affecter,employe,lieu where (affecter.numemp=employe.numemp) and (affecter.ancienlieu=lieu.idlieu)  ");
    while(resultat.next()){
      String a=resultat.getString ("nouveaulieu"); 
        stm=conn.obtenir().createStatement();
  ResultSet ratat = stm.executeQuery("Select province  from lieu where idlieu='"+a+"'");
   while(ratat.next()){  String oe=ratat.getString("province");
 model.addRow(new Object[]{resultat.getString("numaffect"),resultat.getString("nom"),resultat.getString("province"),oe,resultat.getString("dateaffect"),resultat.getString("datepriseservice")});
    }
 
    };
    
    
       } 
    catch(SQLException e){System.err.println(e);}
         
    jtable.setModel(model);   
    
    }
        
         private void deplace(int i){
    try {
  txtidaffect.setText(model.getValueAt(i,0).toString());
   
 txtnom.setText(model.getValueAt(i,1).toString());
    jtancien.setText(model.getValueAt(i,2).toString());
    jtnouveau.setText(model.getValueAt(i,3).toString());
    dateaffect.setText(model.getValueAt(i,4).toString());
    datepris.setText(model.getValueAt(i,5).toString()); 
    }
    catch(Exception e){System.err.println(e);}
    }
         
      private void reinitialiser(){
   txtidaffect.setText(" ");
    txtidemp.setText(" ");
     txtancien.setText(" ");
      txtnew.setText(" ");
       dateaffect.setText("     /  / ");
datepris.setText("    /  / ");
     }
      

    @SuppressWarnings("empty-statement")
      private void afficher()
      {
   
    try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
  ResultSet resultat = stm.executeQuery("Select *  from affecter,employe,lieu where (affecter.numemp=employe.numemp) and (affecter.ancienlieu=lieu.idlieu)  ");
    while(resultat.next()){
      String a=resultat.getString ("nouveaulieu"); 
        stm=conn.obtenir().createStatement();
  ResultSet ratat = stm.executeQuery("Select province  from lieu where idlieu='"+a+"'");
   while(ratat.next()){  String oe=ratat.getString("province");
 model.addRow(new Object[]{resultat.getString("numaffect"),resultat.getString("nom"),resultat.getString("province"),oe,resultat.getString("dateaffect"),resultat.getString("datepriseservice")});
    }
    };
    
    } 
    catch(SQLException e){System.err.println(e);}
 
    jtable.setModel(model);   
      
      
      
      }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtancien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnactu = new javax.swing.JButton();
        btnajout = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtnew = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtidemp = new javax.swing.JTextField();
        txtidaffect = new javax.swing.JTextField();
        dateaffect = new javax.swing.JTextField();
        datepris = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jtancien = new javax.swing.JTextField();
        jtnouveau = new javax.swing.JTextField();
        btnaff = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        imprimerButton = new javax.swing.JButton();
        btnaff1 = new javax.swing.JButton();
        btnmodifier2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EMPLOYEE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("AFFECTER");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("LIEU");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("N°AFFECT :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("N°EMPLOYEE :");

        txtancien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtancien.setForeground(new java.awt.Color(102, 102, 102));
        txtancien.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        txtancien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtancienActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("ANCIEN-LIEU:");

        btnactu.setBackground(new java.awt.Color(255, 0, 0));
        btnactu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactu.setForeground(new java.awt.Color(255, 255, 255));
        btnactu.setText("ACTUALISER");
        btnactu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactuActionPerformed(evt);
            }
        });

        btnajout.setBackground(new java.awt.Color(51, 51, 255));
        btnajout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnajout.setForeground(new java.awt.Color(255, 255, 255));
        btnajout.setText("AJOUTER");
        btnajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        btnmodifier.setBackground(new java.awt.Color(204, 153, 0));
        btnmodifier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmodifier.setForeground(new java.awt.Color(255, 255, 255));
        btnmodifier.setText("MODIFIER");
        btnmodifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        btnsuppr.setBackground(new java.awt.Color(0, 153, 153));
        btnsuppr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(255, 255, 255));
        btnsuppr.setText("SUPPRIMER");
        btnsuppr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("NOUVEAU-LIEU :");

        txtnew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnew.setForeground(new java.awt.Color(102, 102, 102));
        txtnew.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        txtnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("DATE PRISE SERVICE :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("DATE AFFECT :");

        txtidemp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtidemp.setForeground(new java.awt.Color(102, 102, 102));
        txtidemp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        txtidemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidempActionPerformed(evt);
            }
        });

        txtidaffect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtidaffect.setForeground(new java.awt.Color(102, 102, 102));
        txtidaffect.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        txtidaffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidaffectActionPerformed(evt);
            }
        });

        dateaffect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateaffect.setText("        /    /");
        dateaffect.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));

        datepris.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datepris.setText("        /    /");
        datepris.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        datepris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateprisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(txtidemp)
                        .addComponent(txtidaffect)
                        .addComponent(txtancien)
                        .addComponent(dateaffect, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addComponent(txtnew)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12)
                        .addComponent(datepris))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnactu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidaffect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38))
                    .addComponent(txtidemp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtancien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateaffect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datepris, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel15.setBackground(new java.awt.Color(0, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText("TABLE DE MANIPULATION : AFFECTER");

        txtnom.setText("jTextField1");

        jtancien.setText("jTextField2");

        jtnouveau.setText("jTextField3");

        btnaff.setBackground(new java.awt.Color(255, 0, 255));
        btnaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnaff.setForeground(new java.awt.Color(0, 0, 0));
        btnaff.setText("HISTORIQUE");
        btnaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaffActionPerformed(evt);
            }
        });

        jtable.setBackground(new java.awt.Color(255, 255, 255));
        jtable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtable.setForeground(new java.awt.Color(0, 0, 0));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°AFFECT", "N°EMPLOYEE", "ANCIENLIEU", "NOUVEAULIEU", "DATEAFFECT", "DATEPRISESERVICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable);

        imprimerButton.setBackground(new java.awt.Color(204, 255, 204));
        imprimerButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imprimerButton.setForeground(new java.awt.Color(0, 0, 0));
        imprimerButton.setText("IMPRIMER");
        imprimerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimerButton.setMaximumSize(new java.awt.Dimension(96, 23));
        imprimerButton.setMinimumSize(new java.awt.Dimension(96, 23));
        imprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerButtonActionPerformed(evt);
            }
        });

        btnaff1.setBackground(new java.awt.Color(255, 255, 255));
        btnaff1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnaff1.setForeground(new java.awt.Color(0, 0, 0));
        btnaff1.setText("RECHERCHE");
        btnaff1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaff1ActionPerformed(evt);
            }
        });

        btnmodifier2.setBackground(new java.awt.Color(0, 51, 51));
        btnmodifier2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmodifier2.setForeground(new java.awt.Color(255, 255, 255));
        btnmodifier2.setText("EMAIL");
        btnmodifier2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodifier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifier2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imprimerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmodifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnaff, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnaff1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtancien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imprimerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnaff1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmodifier2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtancien, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AFFECTER.super.dispose();
        EMPLOYEE e = new EMPLOYEE();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AFFECTER.super.dispose();
        AFFECTER a = new AFFECTER();
        a.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        AFFECTER.super.dispose();
        LIEU l = new LIEU();
        l.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtancienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtancienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtancienActionPerformed

    private void btnactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactuActionPerformed
        afficher(); reinitialiser();  
    }//GEN-LAST:event_btnactuActionPerformed

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
String idaf=txtidaffect.getText();
       String idempl=txtidemp.getText();
       String ancien=txtancien.getText();
       String news=txtnew.getText();
       String dateaff=dateaffect.getText();
       String datepris=this.datepris.getText();
        String requete= "insert into affecter(numaffect,numemp,ancienlieu, nouveaulieu,dateaffect,datepriseservice ) VALUES ('"+idaf+"','"+idempl+"','"+ancien+"','"+news+"','"+dateaff+"','"+datepris+"') ";
       try{
       stm.executeUpdate(requete);
       JOptionPane.showMessageDialog(null,"employer bien ajouté");
      reinitialiser();
      
       afficher();
               
       }
       catch(Exception ef){JOptionPane.showMessageDialog(null,ef.getMessage());}

       
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnajoutActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
     try {
        if(JOptionPane.showConfirmDialog(null, "confirmer la modification ","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
        { String idempl=txtidemp.getText();
        String idaf=txtidaffect.getText();
       String ancien=txtancien.getText();
       String news=txtnew.getText();
       String dateaff=dateaffect.getText();
       String datepris=this.datepris.getText();
            stm.executeUpdate("Update affecter SET numemp='"+idempl+"',ancienlieu='"+ancien+"',nouveaulieu='"+news+"',dateaffect='"+dateaff+"',datepriseservice='"+datepris+"' WHERE numaffect ="+idaf);
            afficher(); reinitialiser();
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de modifier"+e.getMessage());
        System.err.println(e);
        }

   // TODO add your handling code here:
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
try {
        if(JOptionPane.showConfirmDialog(null, "confirmer la suppression ","suprimer?",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
        {
            if(txtidaffect.getText().length()!= 0){stm.executeUpdate("delete from affecter where numaffect ="+txtidaffect.getText()); reinitialiser();
        
        }
            else {JOptionPane.showMessageDialog(null, "veuillez indiquez l'id de l'employer ");}
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de supprimer car  "+e.getMessage());
        System.err.println(e);
        } afficher();

        // TODO add your handling code here:
    }                                    

    private void supr1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
reinitialiser();    

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsupprActionPerformed

    private void txtnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewActionPerformed

    private void txtidempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempActionPerformed

    private void txtidaffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidaffectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidaffectActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        try{
int i= jtable.getSelectedRow(); deplace(i);


 stm=conn.obtenir().createStatement();
 String exe=txtnom.getText();
              ResultSet result = stm.executeQuery("SELECT numemp FROM employe where nom ='"+exe+"'");
               while(result.next()){
        
 txtidemp.setText(result.getString("numemp"));
 afficher();}
        stm=conn.obtenir().createStatement();
 String axe=jtancien.getText();
              ResultSet res = stm.executeQuery("SELECT idlieu FROM  lieu where province='"+axe+"'");
               while(res.next()){
        
 txtancien.setText(res.getString("idlieu"));
 afficher();
 
 }
                     stm=conn.obtenir().createStatement();
 String ixe=jtnouveau.getText();
              ResultSet ras = stm.executeQuery("SELECT idlieu FROM  lieu where province='"+ixe+"'");
               while(ras.next()){
        
txtnew.setText(ras.getString("idlieu"));
 
 }
               
               afficher();
        }
catch(Exception e){System.out.println(e);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableMouseClicked

    private void btnaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaffActionPerformed
    // Historique des affectations d'un employé
    
      try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
  ResultSet resultat = stm.executeQuery("SELECT * FROM affecter, employe, lieu WHERE (affecter.numemp=employe.numemp) AND (affecter.ancienlieu=lieu.idlieu) ORDER BY dateaffect DESC");

    while(resultat.next()){
         String a=resultat.getString ("nouveaulieu"); 
        stm=conn.obtenir().createStatement();
  ResultSet ratat = stm.executeQuery("Select province  from lieu where idlieu='"+a+"'");
   while(ratat.next()){  String oe=ratat.getString("province");
 model.addRow(new Object[]{resultat.getString("numaffect"),resultat.getString("nom"),resultat.getString("province"),oe,resultat.getString("dateaffect"),resultat.getString("datepriseservice")});
    }
     

    

    };
    stm.close();
    } 
    catch(SQLException e){System.err.println(e);}
         
    jtable.setModel(model);   
    
    
     
    }//GEN-LAST:event_btnaffActionPerformed

    private void dateprisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateprisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateprisActionPerformed

    private void imprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerButtonActionPerformed
try {model.setRowCount(0);
    stm=conn.obtenir().createStatement();
              ResultSet ra= stm.executeQuery("Select *  from employe,affecter,lieu where employe.numemp= ' "+txtidemp.getText()+" ' and  affecter.numemp= ' "+txtidemp.getText()+"'  and(affecter.ancienlieu =lieu.idlieu) ");
             while(ra.next()){
                 String nom = ra.getString("nom");
                 String prenom = ra.getString("prenom");
               String poste = ra.getString("poste");
        String ancienLieu = ra.getString("province");
        String ab = ra.getString("nouveaulieu");
          stm=conn.obtenir().createStatement();
            ResultSet rast= stm.executeQuery("Select *  from lieu where idlieu= "+ab);
        while(rast.next()){
        String nouveauLieu = rast.getString("province");
        String datePriseService = ra.getString("datepriseservice");

        String contenuArrete = generateContenuArrete(nom ,prenom, poste, ancienLieu, nouveauLieu, datePriseService);
        generatePDF(contenuArrete, "Arrêté d'affectation.pdf");}}}
             catch(SQLException e){System.out.println(e);}}
public  String generateContenuArrete(String nom, String prenom, String poste, String ancienLieu, String nouveauLieu, String datePriseService) throws SQLException {
        String a=generateArreteNumber();
        StringBuilder sb = new StringBuilder();
        sb.append(" Arrêté N°"+a+" du ").append(new SimpleDateFormat("dd/MM/yyyy").format(new Date())).append("\n\n");
        sb.append("Mr ").append(nom).append(" ").append(prenom).append(", qui occupe le poste de ").append(poste).append(" à ").append(ancienLieu);
        sb.append(", est affecté à ").append(nouveauLieu).append(" à compter de la date de prise de service ").append(datePriseService).append(".\n");
        sb.append("\nLe présent communiqué sera enregistré et communiqué partout où besoin sera.");
        afficher();
        JOptionPane.showMessageDialog(null, "Le fichier PDF a été généré avec succès !");
        
return sb.toString(); }
        private static String generateArreteNumber(){
        
        Random random =new Random ();
        int arreteNumber = random.nextInt(9000)+1000;
        return String.valueOf(arreteNumber);}
    public static void generatePDF(String content, String outputPath) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(outputPath));
            document.open();
            document.add(new Paragraph(content));
            document.close();
            System.out.println("Le fichier PDF a été généré avec succès !");
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace(); }
    }//GEN-LAST:event_imprimerButtonActionPerformed

    private void btnaff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaff1ActionPerformed
        // TODO add your handling code here:
        AFFECTER.super.dispose();
        ENTREDATE e = new ENTREDATE();
        e.setVisible(true);
    }//GEN-LAST:event_btnaff1ActionPerformed

    private void btnmodifier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifier2ActionPerformed
        // TODO add your handling code here:
         if(txtidemp.getText().length()<=0 || txtnew.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(this, "Selectionnez une ligne pour destinnataire");
        }
        else
        {
            int  numemp = Integer.parseInt(txtidemp.getText());
            int nlieu =  Integer.parseInt(txtnew.getText());

            try
            {
                Connection conn1;
                PreparedStatement insert;
                Class.forName("org.postgresql.Driver");
                conn1 = DriverManager.getConnection("jdbc:postgresql://localhost:5432/employee_gestion","postgres","root");
                insert = conn1.prepareStatement("select employe.civilite, employe.nom, employe.prenom, employe.mail, lieu.design, lieu.province from (( employe inner join affecter on employe.numemp = ?) inner join lieu on lieu.idlieu = ?)");
                insert.setInt(1,numemp);
                insert.setInt(2,nlieu);

                ResultSet rs = insert.executeQuery();

                rs.next();
                String civilite = rs.getString("civilite");
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                String mail = rs.getString("mail");
                String nlieuaff = rs.getString("design");
                String nlieuaffprov = rs.getString("province");

                Properties props = new Properties();
                props.put("mail.smtp.host", "smtp.mail.com");
                props.put("mail.smtp.socketFactory.port", "465");
                props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                props.put("mail.smtp.auth", "true");
              props.put("mail.smtp.port", "465");

                props.put("mail.smtp.ssl.checkserveridentity", true);
                
                
               Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("michaelramana2021@gmail.com", "nyvkidvhfpqzecrd");
            }
        });
                try
                {
                    Message msg = new MimeMessage(session);
                    msg.setFrom(new InternetAddress("michaelramana2021@gmail.com"));
                    msg.addRecipient(Message.RecipientType.TO, new InternetAddress(mail));
                    msg.setSubject("Avis d'affectation");
                    msg.setText("Bonjour,\n "+civilite+" "+nom+" "+prenom+" , nous vous informons de votre prochaine affectation à "+nlieuaff+" "+nlieuaffprov+". "
                            + "\n\nNous vous ferons parvenir dans les plus brefs délais un arrêté pour plus d'informations.");
                    Transport.send(msg);

                    JOptionPane.showMessageDialog(null, "Email envoyé");
                }
                catch(HeadlessException | MessagingException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }   catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnmodifier2ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFFECTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFFECTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFFECTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFFECTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFFECTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactu;
    private javax.swing.JButton btnaff;
    private javax.swing.JButton btnaff1;
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnmodifier2;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JTextField dateaffect;
    private javax.swing.JTextField datepris;
    private javax.swing.JButton imprimerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField jtancien;
    private javax.swing.JTextField jtnouveau;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtancien;
    private javax.swing.JTextField txtidaffect;
    private javax.swing.JTextField txtidemp;
    private javax.swing.JTextField txtnew;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
