/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu.dash;
import java.awt.HeadlessException;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import java.sql.*;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mon PC
 */
public class EMPLOYEE extends javax.swing.JFrame {
    connexion conn= new connexion();
    Statement stm;
    ResultSet resultat;
    DefaultTableModel model= new DefaultTableModel();

    /**
     * Creates new form EMPLOYEE
     */
    public EMPLOYEE() {
        initComponents();
         model.addColumn("N°EMPLOYEE");
        model.addColumn("CIVILITE");
        model.addColumn("NOM");
        model.addColumn("PRENOM");
        model.addColumn("MAIL");
        model.addColumn("POSTE");
        model.addColumn("LIEU");
        
        try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
    ResultSet resultat = stm.executeQuery("SELECT numemp, civilite, nom, prenom, mail, poste, province, lieu FROM public.employe,lieu where(employe.lieu=lieu.idlieu)");
    while(resultat.next()){
        
 model.addRow(new Object[]{resultat.getString("numemp"),resultat.getString("civilite"),resultat.getString("nom"),resultat.getString("prenom"),resultat.getString("mail"),resultat.getString("poste"),resultat.getString("province")});
    };
    }
        
    catch(SQLException e){System.err.println(e);}
           jttable.setModel(model);  
           
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void deplace(int i){
    try {
  jtnum.setText(model.getValueAt(i,0).toString());
   
    jtnom.setText(model.getValueAt(i,2).toString());
    jtprenom.setText(model.getValueAt(i,3).toString());
    jtmail.setText(model.getValueAt(i,4).toString());
    jtposte.setText(model.getValueAt(i,5).toString());
    txtex.setText(model.getValueAt(i,6).toString());
    jtci.setSelectedItem(model.getValueAt(i,1).toString());


   
    }
    catch(Exception e){System.err.println(e);}
    }
    private void reinitialiser(){
     jtnum.setText(" ");
     jtnom.setText(" ");
     jtprenom.setText(" ");jtmail.setText(" ");jtlieu.setText(" ");jtposte.setText(" ");
     }
      private void afficher(){
  try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
    ResultSet resultat = stm.executeQuery("SELECT numemp,civilite,nom,prenom,mail,poste, province\n" + "FROM public.employe,lieu where(employe.lieu=lieu.idlieu);");
    while(resultat.next()){
 model.addRow(new Object[]{resultat.getString("numemp"),resultat.getString("civilite"),resultat.getString("nom"),resultat.getString("prenom"),resultat.getString("mail"),resultat.getString("poste"),resultat.getString("province")});
    };
    }
    catch(SQLException e){System.err.println(e);}
   
    jttable.setModel(model);    }
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jttable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnactualier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtprenom = new javax.swing.JTextField();
        jtci = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtposte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtlieu = new javax.swing.JTextField();
        btnajouter = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        txtR = new javax.swing.JTextField();
        btnR = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtex = new javax.swing.JTextField();
        jtchoix = new javax.swing.JComboBox<>();
        btnsuppr1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EMPLOYEE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("AFFECTER");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("LIEU");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jttable.setBackground(new java.awt.Color(240, 240, 240));
        jttable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "CIVILITE", "NOM", "PRENOM", "MAIL", "POSTE", "LIEU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jttable);
        if (jttable.getColumnModel().getColumnCount() > 0) {
            jttable.getColumnModel().getColumn(0).setMinWidth(1);
            jttable.getColumnModel().getColumn(0).setPreferredWidth(1);
            jttable.getColumnModel().getColumn(1).setMinWidth(2);
            jttable.getColumnModel().getColumn(1).setPreferredWidth(3);
            jttable.getColumnModel().getColumn(2).setMinWidth(2);
            jttable.getColumnModel().getColumn(2).setPreferredWidth(2);
            jttable.getColumnModel().getColumn(3).setMinWidth(2);
            jttable.getColumnModel().getColumn(3).setPreferredWidth(2);
            jttable.getColumnModel().getColumn(6).setMinWidth(2);
            jttable.getColumnModel().getColumn(6).setPreferredWidth(2);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("N°EMPLOYEE :");

        jtmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtmail.setForeground(new java.awt.Color(102, 102, 102));
        jtmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtmailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CIVILITE :");

        jtnom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtnom.setForeground(new java.awt.Color(102, 102, 102));
        jtnom.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NOM :");

        btnactualier.setBackground(new java.awt.Color(255, 0, 0));
        btnactualier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualier.setForeground(new java.awt.Color(255, 255, 255));
        btnactualier.setText("ACTUALISER");
        btnactualier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualierActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PRENOM :");

        jtprenom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtprenom.setForeground(new java.awt.Color(102, 102, 102));
        jtprenom.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtprenomActionPerformed(evt);
            }
        });

        jtci.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtci.setForeground(new java.awt.Color(102, 102, 102));
        jtci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner", "Mr", "Mlle", "Mme" }));
        jtci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtciActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("MAIL :");

        jtposte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtposte.setForeground(new java.awt.Color(102, 102, 102));
        jtposte.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jtposte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtposteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("POSTE :");

        jtnum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtnum.setForeground(new java.awt.Color(102, 102, 102));
        jtnum.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("LIEU :");

        jtlieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtlieu.setForeground(new java.awt.Color(102, 102, 102));
        jtlieu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jtlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlieuActionPerformed(evt);
            }
        });

        btnajouter.setBackground(new java.awt.Color(51, 51, 255));
        btnajouter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnajouter.setForeground(new java.awt.Color(255, 255, 255));
        btnajouter.setText("AJOUTER");
        btnajouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        btnmodifier.setBackground(new java.awt.Color(204, 153, 0));
        btnmodifier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmodifier.setForeground(new java.awt.Color(255, 255, 255));
        btnmodifier.setText("MODIFIER");
        btnmodifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        btndel.setBackground(new java.awt.Color(0, 153, 153));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 255, 255));
        btndel.setText("SUPPRIMER");
        btndel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnactualier, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtci, javax.swing.GroupLayout.Alignment.LEADING, 0, 272, Short.MAX_VALUE)
                            .addComponent(jtnom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtprenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtposte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtlieu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtnum, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtposte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        txtR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtR.setForeground(new java.awt.Color(102, 102, 102));
        txtR.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        txtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRActionPerformed(evt);
            }
        });

        btnR.setBackground(new java.awt.Color(255, 255, 255));
        btnR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnR.setForeground(new java.awt.Color(0, 0, 0));
        btnR.setText("RECHERCHE");
        btnR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("TABLE DE MANIPULATION : EMPLOYEE");

        txtex.setText("jTextField1");

        jtchoix.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "PRENOM" }));
        jtchoix.setBorder(new javax.swing.border.MatteBorder(null));
        jtchoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtchoixActionPerformed(evt);
            }
        });

        btnsuppr1.setBackground(new java.awt.Color(0, 0, 102));
        btnsuppr1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsuppr1.setForeground(new java.awt.Color(255, 255, 255));
        btnsuppr1.setText("LISTE NON AFFECTER");
        btnsuppr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuppr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuppr1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtex, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsuppr1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR)
                    .addComponent(jtchoix)
                    .addComponent(btnsuppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(78, 78, 78)
                .addComponent(txtex, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EMPLOYEE.super.dispose();
        EMPLOYEE e = new EMPLOYEE();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EMPLOYEE.super.dispose();
        AFFECTER a = new AFFECTER();
        a.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        EMPLOYEE.super.dispose();
        LIEU l = new LIEU();
        l.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtmailActionPerformed

    private void jtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnomActionPerformed

    private void btnactualierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualierActionPerformed
        afficher(); reinitialiser();  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactualierActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
       String id=jtnum.getText();
        String nom=jtnom.getText();
        String prenom=jtprenom.getText();
        String civilite=jtci.getSelectedItem().toString();
        String poste=jtposte.getText();
        String lieu=jtlieu.getText();
        String mail=jtmail.getText();
        String requete= "insert into employe(numemp,\"civilite\", nom, prenom, mail, poste, lieu ) VALUES ('"+id+"','"+civilite+"','"+nom+"','"+prenom+"','"+mail+"','"+poste+"','"+lieu+"') ";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null,"employer bien ajouté");
       reinitialiser();

            afficher();

        }
        catch(Exception ef){JOptionPane.showMessageDialog(null,ef.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(null, "confirmer la modification ","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
            {  String id=jtnum.getText();
                String nom=jtnom.getText();
                String prenom=jtprenom.getText();
                String civilite=jtci.getSelectedItem().toString();
                String poste=jtposte.getText();
                String lieu=jtlieu.getText();
                String mail=jtmail.getText();
                stm.executeUpdate("Update employe SET civilite='"+civilite+"',nom='"+nom+"',prenom='"+prenom+"',mail='"+mail+"',poste='"+poste+"',lieu='"+lieu+"' WHERE numemp ="+id);
                afficher(); reinitialiser();
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de modifier"+e.getMessage());
            System.err.println(e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
try {
            if(JOptionPane.showConfirmDialog(null, "confirmer la suppression ","supprimer?",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
            {
                if(jtnum.getText().length()!= 0){stm.executeUpdate("delete from employe where numemp ="+jtnum.getText()); reinitialiser();

                }
                else {JOptionPane.showMessageDialog(null, "veuillez indiquez l'id de l'employer ");}
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de supprimer car  "+e.getMessage());
            System.err.println(e);
        } afficher();        // TODO add your handling code here:
    }//GEN-LAST:event_btndelActionPerformed

    private void jtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtprenomActionPerformed

    private void jtposteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtposteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtposteActionPerformed

    private void jtlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlieuActionPerformed

    private void jtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnumActionPerformed

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
String choix =jtchoix.getSelectedItem().toString();
        if(choix =="NOM"){

try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
    String re=txtR.getText();
    ResultSet resultat = stm.executeQuery("Select *  from employe where nom LIKE '%"+re+"%'");
    while(resultat.next()){
 model.addRow(new Object[]{resultat.getString("numemp"),resultat.getString("civilite"),resultat.getString("nom"),resultat.getString("prenom"),resultat.getString("mail"),resultat.getString("poste"),resultat.getString("lieu")});
    };
    }
    catch(SQLException e){System.err.println(e);}
   
    jttable.setModel(model);   }
        else {
            try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
    String re=txtR.getText();
    ResultSet resultat = stm.executeQuery("Select *  from employe where prenom LIKE '%"+re+"%'");
    while(resultat.next()){
 model.addRow(new Object[]{resultat.getString("numemp"),resultat.getString("civilite"),resultat.getString("nom"),resultat.getString("prenom"),resultat.getString("mail"),resultat.getString("poste"),resultat.getString("lieu")});
    };
    }
    catch(SQLException e){System.err.println(e);}
   
    jttable.setModel(model);
        
        
        
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRActionPerformed

    private void jttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jttableMouseClicked
     try{
            int i= jttable.getSelectedRow(); deplace(i);
            String exe=txtex.getText();
             model.setRowCount(0);
              stm=conn.obtenir().createStatement();
              ResultSet resultat = stm.executeQuery("SELECT idlieu FROM public.lieu where province ='"+exe+"'");
               while(resultat.next()){
        
 jtlieu.setText(resultat.getString("idlieu"));
 afficher();
    };
        }
        catch(Exception e){System.out.println(e);
        
        }
        
           // TODO add your handling code here:
    }//GEN-LAST:event_jttableMouseClicked

    private void jtchoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtchoixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtchoixActionPerformed

    private void btnsuppr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuppr1ActionPerformed
// LISTE DES PERSONNE PAS ENCORE AFFECTER         
        String url = "jdbc:postgresql://localhost:5432/employee_gestion";
        String user = "postgres";
        String password = "root";



          try{
    model.setRowCount(0);
    stm=conn.obtenir().createStatement();
    ResultSet resultat = stm.executeQuery("SELECT * FROM employe,lieu WHERE( numemp NOT IN (SELECT numemp FROM AFFECTER)) and (employe.lieu=lieu.idlieu)");
    while(resultat.next()){
        
 model.addRow(new Object[]{resultat.getString("numemp"),resultat.getString("civilite"),resultat.getString("nom"),resultat.getString("prenom"),resultat.getString("mail"),resultat.getString("poste"),resultat.getString("province")});
    };
    }
        
    catch(SQLException e){System.err.println(e);}
           jttable.setModel(model);  
           
    
        
    }//GEN-LAST:event_btnsuppr1ActionPerformed

    private void jtciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPLOYEE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnactualier;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnsuppr1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jtchoix;
    private javax.swing.JComboBox<String> jtci;
    private javax.swing.JTextField jtlieu;
    private javax.swing.JTextField jtmail;
    private javax.swing.JTextField jtnom;
    private javax.swing.JTextField jtnum;
    private javax.swing.JTextField jtposte;
    private javax.swing.JTextField jtprenom;
    private javax.swing.JTable jttable;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtex;
    // End of variables declaration//GEN-END:variables
}
